# ===============    Disk Usage  configuration ======================================================================
# 
#
#
#  
#
# WATCH_PATH: directory to monitor
WATCH_PATH="/mnt"

# LOG_FILE:  where usage records are kept   
LOG_FILE="/var/log/Dsk.log"

# MAX_LOG_LINES: rotate log after this many lines
MAX_LOG_LINES=250 


# Dang: INTERVER FOR EACH LOOP 
Dang=120 


# 
# WARN_PERCENT:  set max limit for file system to alert 
WARN_PERCENT=96 



#
#
#
# 
#

