# ===============    Disk Usage  configuration ======================================================================
# 
#
#
# plug in path to of the mounting disk 
#
# WATCH_PATH: 
WATCH_PATH="/mnt"

# LOG_FILE:    
LOG_FILE="/var/log/Dsk.log"

# MAX_LOG_LINES: 
MAX_LOG_LINES=250 


# INTERVER FOR EACH LOOP 
Dang=120 


# 
# set max limit for file system to alert 
WARN_PERCENT=3 



#
#
#
# 
#

