# ===============    Disk Usage  configuration ======================================================================
# 
#
#
# plug in path to of the mounting disk 
#
# WATCH_PATH: 
WATCH_PATH="/mnt/usmanlab"

# LOG_FILE:    
LOG_FILE="/var/log/Dsk.log"

# MAX_LOG_LINES: 
MAX_LOG_LINES=10000 


# INTERVER FOR EACH LOOP 
Dang=180 


# 
# set max limit for file system to alert 
WARN_PERCENT=96 



#
#
#
# 
#

